#Build settings
markdown: kramdown
# theme: jekyll-theme-tactile

title: David De Ridder
email: david.deridder@unige.ch
description: >- # this means to ignore newlines until "baseurl:"
  PhD student at the University of Geneva and the EPFL (Ecole Polytechnique Fédérale de Lausanne)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://daderidd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daderidd
github_username:  daderidd

# Build settings
theme: minima
plugins:
  - jekyll-feed
